[timers]
url_load_interval = 24          # Hours, new url will get load after this interval
url_file_read_interval = 1      # Minutes, examines any update on url_file input on this interval
refresh_url_interval = 60       # Minutes, url will get refresh after this interval
# NOTE : refresh_url_interval should less than url_load_interval

[settings]
retain_last_url = True
# True : browser will be loaded with last url from file. It wont get closed until manual interruption.
# False : after last url from input file script gets exit.
load_urls_round_robin = true
# true : reads url file round robin fashion
# false : stays at last url from input url_file, until new url/urls added